In [1]:
import torch

In [3]:
a = torch.tensor([1, 2, 3])
print(a.ndim)
print(a.dtype)

1
torch.int64


In [4]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
print(a)

tensor([1., 2., 3.])


In [5]:
x=torch.tensor([[1,2,3], [4,5,6]])
print(x.ndim)
print(x.shape)
print(x.dtype)

2
torch.Size([2, 3])
torch.int64


In [7]:
y=torch.tensor([1.0,2.0,3.0])
print(y.dtype)

z=torch.tensor(5)
print(z.ndim)
print(z.shape)

torch.float32
0
torch.Size([])


# Zeros function
- we can also use .rand, .ones

In [13]:
b = torch.zeros(3, dtype=torch.float32)
print(b)

b = torch.zeros([10, 10], dtype=torch.float32)
print(b)

b = torch.zeros([3, 3, 3], dtype=torch.float32)
print(b)

tensor([0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [16]:
a = torch.arange(10)
print(a)
print(f'{a=}')


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
